[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/news.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/json; charset=utf-8"
